// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyzEBjT8EMUIsOzmIHaVBT2HySgzfyYmU',
    appId: '1:839725278101:web:8353461ed668736b5f8c9c',
    messagingSenderId: '839725278101',
    projectId: 'jeytracker',
    authDomain: 'jeytracker.firebaseapp.com',
    storageBucket: 'jeytracker.firebasestorage.app',
    measurementId: 'G-F6GN76R2YY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY04t2yMWrn6HwqeWANeXtWXRGujPnMzg',
    appId: '1:839725278101:android:cc213e80b9418d9a5f8c9c',
    messagingSenderId: '839725278101',
    projectId: 'jeytracker',
    storageBucket: 'jeytracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZ5yEun_bQmH6DfMaDOwfTcHSNsUbcXog',
    appId: '1:839725278101:ios:61c7cceb622b83c95f8c9c',
    messagingSenderId: '839725278101',
    projectId: 'jeytracker',
    storageBucket: 'jeytracker.firebasestorage.app',
    iosBundleId: 'com.example.organizationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZ5yEun_bQmH6DfMaDOwfTcHSNsUbcXog',
    appId: '1:839725278101:ios:61c7cceb622b83c95f8c9c',
    messagingSenderId: '839725278101',
    projectId: 'jeytracker',
    storageBucket: 'jeytracker.firebasestorage.app',
    iosBundleId: 'com.example.organizationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyzEBjT8EMUIsOzmIHaVBT2HySgzfyYmU',
    appId: '1:839725278101:web:a97d2a2acb246c9d5f8c9c',
    messagingSenderId: '839725278101',
    projectId: 'jeytracker',
    authDomain: 'jeytracker.firebaseapp.com',
    storageBucket: 'jeytracker.firebasestorage.app',
    measurementId: 'G-3J3KC5EXVD',
  );
}
